

import 'package:drivecare/src/data/models/apptheme.dart';
import 'package:drivecare/src/utils/constants/hexcolor.dart';

class Themes {
  static List<AppTheme> theme = [
    AppTheme(
      primaryColor: HexColor.fromHex("#93CEEC"),
      secondaryColor: HexColor.fromHex("#F0F0F0"),
      alternateColor: HexColor.fromHex("#E8E3E0"),
      primaryTextColor: HexColor.fromHex("#004464"),
      secondaryTextColor: HexColor.fromHex("#E7CF2B"),
      alternateTextColor: HexColor.fromHex("#717171"),
      tileColors: [
        HexColor.fromHex("#93CEEC"),
        HexColor.fromHex("#E8E3E0"),
        HexColor.fromHex("#F0F0F0"),
      ],
      tileTextColors: [
        HexColor.fromHex("#004465"),
        HexColor.fromHex("#717171"),
        HexColor.fromHex("#E7CF2B"),
      ],
      categoryColor: HexColor.fromHex('#FFC478'),
      categoryTextColor: HexColor.fromHex('#3A6D87'),
      catgoriesImage: 'assets/images/Group 1171274726 (1).png',
      productColor: HexColor.fromHex('#FFF6B6'),
      productTextColor: HexColor.fromHex('#C9B009'),
      productImage: 'assets/images/Group 1171274727 (2).png',
      filterColor: HexColor.fromHex('#74D9C1'),
      filterTextColor: HexColor.fromHex('#008C6A'),
      filterImage: 'assets/images/Vector (4).png',
      settingsColor: HexColor.fromHex('#D9D9D9'),
      settingsTextColor: HexColor.fromHex('#7D000000'),
      settingsImage: 'assets/images/Group 1171274728.png',
      analyticsColor: HexColor.fromHex('#F0F0F0'),
      analyticsTextColor: HexColor.fromHex('#3B6E87'),
      analyticsImage: 'assets/images/Group 1171274750.png',
    ),
    AppTheme(
      primaryColor: HexColor.fromHex("#60BE68"),
      secondaryColor: HexColor.fromHex("#EBFFF0"),
      alternateColor: HexColor.fromHex("#E8E3E0"),
      primaryTextColor: HexColor.fromHex("#008E54"),
      secondaryTextColor: HexColor.fromHex("#E7D02B"),
      alternateTextColor: HexColor.fromHex("#E7D02B"),
      tileColors: [
        HexColor.fromHex('#9FEAA6'),
        HexColor.fromHex("#F5FFFB"),
        HexColor.fromHex("#EBFFF0"),
      ],
      tileTextColors: [
        HexColor.fromHex("#008E54"),
        HexColor.fromHex("#717171"),
        HexColor.fromHex("#E7CF2B"),
      ],
      categoryColor: HexColor.fromHex('#60BE68'),
      categoryTextColor: HexColor.fromHex('#3A6D87'),
      catgoriesImage: 'assets/images/Group 1171274726 (2).png',
      productColor: HexColor.fromHex('#EBFFF0'),
      productTextColor: HexColor.fromHex('#C9B009'),
      productImage: 'assets/images/Group 1171274727 (2).png',
      filterColor: HexColor.fromHex('#74D9C1'),
      filterTextColor: HexColor.fromHex('#008C6A'),
      filterImage: 'assets/images/Vector (4).png',
      settingsColor: HexColor.fromHex('#D9D9D9'),
      settingsTextColor: HexColor.fromHex('#7D000000'),
      settingsImage: 'assets/images/Group 1171274728 (1).png',
      analyticsColor: HexColor.fromHex('#F0F0F0'),
      analyticsTextColor: HexColor.fromHex('#3B6E87'),
      analyticsImage: 'assets/images/Group 1171274750.png',
    ),
    AppTheme(
      primaryColor: HexColor.fromHex("#FFA938"),
      secondaryColor: HexColor.fromHex("#FFFAE0"),
      alternateColor: HexColor.fromHex("#E8E3E0"),
      primaryTextColor: HexColor.fromHex("#FE8B30"),
      secondaryTextColor: HexColor.fromHex("#F58B29"),
      alternateTextColor: HexColor.fromHex("#FFB375"),
      tileColors: [
        HexColor.fromHex("#FFC478"),
        HexColor.fromHex("#FAFAFA"),
        HexColor.fromHex("#FFFAE0"),
      ],
      tileTextColors: [
        HexColor.fromHex("#FE8B30"),
        HexColor.fromHex("#717171"),
        HexColor.fromHex("#F58B29"),
      ],
      categoryColor: HexColor.fromHex('#FFC478'),
      categoryTextColor: HexColor.fromHex('#3A6D87'),
      catgoriesImage: 'assets/images/Group 1171274726 (3).png',
      productColor: HexColor.fromHex('#FFF6B6'),
      productTextColor: HexColor.fromHex('#C9B009'),
      productImage: 'assets/images/Group 1171274727 (3).png',
      filterColor: HexColor.fromHex('#74D9C1'),
      filterTextColor: HexColor.fromHex('#008C6A'),
      filterImage: 'assets/images/Vector (4).png',
      settingsColor: HexColor.fromHex('#D9D9D9'),
      settingsTextColor: HexColor.fromHex('#7D000000'),
      settingsImage: 'assets/images/Group 1171274728 (1).png',
      analyticsColor: HexColor.fromHex('#F0F0F0'),
      analyticsTextColor: HexColor.fromHex('#3B6E87'),
      analyticsImage: 'assets/images/Group 1171274750.png',
    ),
  ];
}
